### ISSUE TITLE
Remote Control

### ISSUE THREAD

**Issue by aspeteRakete** [kr15h/ofxPiMapper#6]
To be truly useable an Application for remote Controlling the App would be great. Have you looked into that? I would suggest doing it over OSC and mirror the scene on the Remote Controlling device.

**Comment by magdesign** [comment]
I'm trying to remote control with xdotool.
This would be a very simple solution to control PiMapper over a Webserver (already wrote some simple interface).
While testing it works for all sorts of programms exept for the ofxPiMapper, how do you load the keyboard in openframeworks?
Is it listening to a hardware binded keyboard, might it be possible to listen to systems keyboard?

Maybe someone can give me a hint.

**Comment by magdesign** [comment]
Solved:
I finally created a fake keyboard with the uinput command and the help of his tools:
http://www.fsays.eu/Blogging/Blog/Details/23
with fsayskeyboard its now possible to send remote keyboard commands.
Next step will be the mouse.....

**Comment by kr15h** [comment]
The trick I want to do here is to create an OSC interface that would allow to send messages from other devices in the same network.

**Comment by kr15h** [comment]
And before I do that, I want to make use of the [Command Design Pattern](http://sourcemaking.com/design_patterns/command) to bootstrap undo support in future versions as well.

**Comment by magdesign** [comment]
OSC sounds great, 
however,
Is there a possibility to change the key assignment.
for example I want to delete a surface with the 'D' button...?

**Comment by kr15h** [comment]
I am thinking towards creating a TCP-based API for this.

**Comment by reno-** [comment]
Hi,
I just tried PiMapper and I love it !
I would be perfect to remote it through OSC, Artnet (control from a lighting board), or TCP.

Maybe a python API could solve the issue as it might be simple to create differents protocols implementations with a python API?
just my 2 cents…

**Comment by magdesign** [comment]
TCP already works emulating an usb keyboard... its a bit of a hack, but it works....
https://github.com/magdesign/PocketVJ-CP-v3

**Comment by magdesign** [comment]
Working on new approaches for remote control PiMapper using:
- vnc screensharing (very slow and laggy)
- nomachine remote desktop
- virtualgl
- gstreamer (with this, mouse and keyboard emulation is still an issue)
- uv4l (limited to 640x480 for the moment)

The nomachine approach looks promising, for the moment i'm struggling rendering PiMapper's output since its not rendered into the x-window system, so looking for a solution to grab the (i guess its) OpenGL_ES OpenVG.

I know that when using an x-window system we loose a bit of performance... Anyone any idea on this?

**Comment by kr15h** [comment]
The way I want to go is opening a TCP API.

**Comment by kr15h** [comment]
I am close. Right now I am decoupling the keyboard shortcuts. Basically I am almost finished with having all the shortcuts as ofxPiMapper class methods. One would then add a TCP layer on top of it and it would be possible to create two example applications:

1. TCP sender (the controller on one's laptop)
2. TCP receiver (running on a raspi)

**Comment by magdesign** [comment]
cool. 
That means I stop spending more time on my screenshare "hacks"...

**Comment by kr15h** [comment]
Yes.

**Comment by a0n** [comment]
@kr15h would you like to put your current satus in a branch?

**Comment by kr15h** [comment]
I have it ready actually. I have to add it as an example. Currently a too busy with organizing an event. Next week will add it.

**Comment by kr15h** [comment]
For the ones involved in this discussion, I finally added remote control capability as examples. There are two of those.

- example_remote-server
- example-remote-client

I decided to leave them as examples rather than integrating TCP code into ofxPiMapper core, which I would prefer focused on the primary task - projection mapping. For the bundled version (the iso file) I would make it so that one can connect with the remote from a remote PC. 

I will add basic instructions on how to use this as soon as I can.

**Comment by magdesign** [comment]
Amazing!
Really looking forward to test this.
So I have to compile a client on my computer to control the PiMapper on the RPi, right?

**Comment by kr15h** [comment]
You have to compile the server example on RPi as well @magdesign

**Comment by kr15h** [comment]
But when I pull together the `.img` file, the TCP server will be there.

**Comment by controla** [comment]
This is working perfectly, testing it right now. Had to mess with xrandr panning in the client to simulate the same resolution as the pi. All works so far except for the arrow keys. Is there a way to enable them or replace the binding?

**Comment by kr15h** [comment]
Have to look into that. There are many options there. Have to test and decide what would be best. The problem with arrows and shift is that they are defined as OF constants.

**Comment by kr15h** [comment]
OK, since the remote control option is there, I will close this now and open up bug issues for each improvement we want to make.
